"""
Email Templates — Jinja2-based HTML email templates for daily, weekly, and monthly digests.

All templates use inline CSS for maximum email client compatibility.
"""

import logging
from typing import List, Dict, Any
from datetime import datetime

from jinja2 import Template

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────
# Shared Styles
# ──────────────────────────────────────────────

_BASE_STYLES = """
body { margin: 0; padding: 0; background-color: #0f0f13; font-family: 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; color: #e0e0e0; }
.container { max-width: 680px; margin: 0 auto; padding: 0; }
.header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%); padding: 32px 24px; text-align: center; border-bottom: 3px solid #00d4ff; }
.header h1 { color: #ffffff; font-size: 24px; margin: 0 0 8px 0; }
.header .subtitle { color: #a0c4ff; font-size: 14px; margin: 0; }
.badge { display: inline-block; background: #00d4ff22; color: #00d4ff; border: 1px solid #00d4ff44; border-radius: 12px; padding: 4px 12px; font-size: 12px; margin: 4px; }
.content { padding: 24px; background-color: #1a1a24; }
.paper-card { background: #22223a; border-radius: 12px; padding: 20px; margin-bottom: 20px; border-left: 4px solid #00d4ff; }
.paper-card h3 { color: #ffffff; margin: 0 0 8px 0; font-size: 18px; }
.paper-card .authors { color: #8888aa; font-size: 13px; margin-bottom: 12px; }
.paper-card .summary { color: #ccccdd; font-size: 14px; line-height: 1.7; }
.paper-card .meta { margin-top: 12px; font-size: 12px; color: #6666aa; }
.btn { display: inline-block; background: linear-gradient(135deg, #00d4ff, #0080ff); color: #ffffff !important; text-decoration: none; padding: 10px 20px; border-radius: 8px; font-size: 14px; font-weight: 600; margin-top: 12px; }
.stats-row { display: flex; justify-content: space-around; padding: 16px; background: #16162a; border-radius: 8px; margin-bottom: 20px; }
.stat { text-align: center; }
.stat .number { font-size: 28px; font-weight: 700; color: #00d4ff; }
.stat .label { font-size: 12px; color: #8888aa; }
.footer { padding: 24px; text-align: center; font-size: 12px; color: #555; background: #0f0f13; }
.footer a { color: #00d4ff; text-decoration: none; }
.toc { background: #16162a; border-radius: 8px; padding: 16px; margin-bottom: 20px; }
.toc h4 { color: #00d4ff; margin: 0 0 8px 0; }
.toc ul { margin: 0; padding-left: 20px; }
.toc li { color: #aaaacc; font-size: 14px; margin-bottom: 4px; }
.day-section { margin-bottom: 24px; }
.day-section h3 { color: #00d4ff; border-bottom: 1px solid #333; padding-bottom: 8px; }
"""

# ──────────────────────────────────────────────
# Daily Template
# ──────────────────────────────────────────────

_DAILY_TEMPLATE = Template("""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>{{ styles }}</style></head>
<body>
<div class="container">
    <div class="header">
        <h1>📚 Daily Research Digest</h1>
        <p class="subtitle">{{ topic }} — {{ date }}</p>
        <div style="margin-top: 12px;">
            <span class="badge">📄 {{ paper_count }} papers</span>
            <span class="badge">📖 {{ word_count }} words</span>
            <span class="badge">⏱️ ~{{ reading_time }} min read</span>
        </div>
    </div>
    <div class="content">
        {% if greeting_name %}
        <div style="padding: 20px 0 12px 0; font-size: 16px; color: #e0e0e0;">
            👋 Hi <strong style="color: #ffffff;">{{ greeting_name }}</strong>,
            <br><span style="color: #a0c4ff;">Here's your daily research digest — freshly curated just for you.</span>
        </div>
        {% endif %}
        {% for paper in papers %}
        <div class="paper-card">
            <h3>{{ paper.title }}</h3>
            <div class="authors">{{ paper.authors }}</div>
            <div class="summary">{{ paper.summary_html }}</div>
            <div class="meta">
                {% if paper.url %}<a href="{{ paper.url }}" class="btn">Read Full Paper →</a>{% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="footer">
        <p>Generated by <a href="https://github.com/Raj-Shriwastav/Research_Paper_Summarizer">Research Paper Summarizer</a></p>
        <p>You received this because you're subscribed to daily digests.</p>
    </div>
</div>
</body></html>""")


# ──────────────────────────────────────────────
# Weekly Template
# ──────────────────────────────────────────────

_WEEKLY_TEMPLATE = Template("""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>{{ styles }}</style></head>
<body>
<div class="container">
    <div class="header">
        <h1>📅 Weekly Research Roundup</h1>
        <p class="subtitle">{{ topic }} — Week of {{ week_start }} to {{ week_end }}</p>
        <div style="margin-top: 12px;">
            <span class="badge">📄 {{ total_papers }} papers</span>
            <span class="badge">📅 {{ days_count }} days</span>
            <span class="badge">📖 {{ total_words }} words</span>
        </div>
    </div>
    <div class="content">
        {% if greeting_name %}
        <div style="padding: 20px 0 12px 0; font-size: 16px; color: #e0e0e0;">
            👋 Hi <strong style="color: #ffffff;">{{ greeting_name }}</strong>,
            <br><span style="color: #a0c4ff;">Here's your weekly research roundup — the best papers from this week.</span>
        </div>
        {% endif %}
        <div class="toc">
            <h4>📋 This Week's Highlights</h4>
            <ul>
            {% for day in days %}
                <li><strong>{{ day.date }}:</strong> {{ day.paper_titles | join(', ') }}</li>
            {% endfor %}
            </ul>
        </div>
        {% for day in days %}
        <div class="day-section">
            <h3>{{ day.date }} ({{ day.paper_count }} papers)</h3>
            {{ day.content_html }}
        </div>
        {% endfor %}
    </div>
    <div class="footer">
        <p>Generated by <a href="https://github.com/Raj-Shriwastav/Research_Paper_Summarizer">Research Paper Summarizer</a></p>
        <p>You received this because you're subscribed to weekly digests.</p>
    </div>
</div>
</body></html>""")


# ──────────────────────────────────────────────
# Monthly Template
# ──────────────────────────────────────────────

_MONTHLY_TEMPLATE = Template("""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>{{ styles }}</style></head>
<body>
<div class="container">
    <div class="header">
        <h1>📊 Monthly Research Report</h1>
        <p class="subtitle">{{ topic }} — {{ month_name }} {{ year }}</p>
        <div style="margin-top: 12px;">
            <span class="badge">📄 {{ total_papers }} papers</span>
            <span class="badge">📅 {{ weeks_count }} weeks</span>
            <span class="badge">📖 {{ total_words }} words</span>
        </div>
    </div>
    <div class="content">
        {% if greeting_name %}
        <div style="padding: 20px 0 12px 0; font-size: 16px; color: #e0e0e0;">
            👋 Hi <strong style="color: #ffffff;">{{ greeting_name }}</strong>,
            <br><span style="color: #a0c4ff;">Here's your monthly research report — a deep dive into this month's highlights.</span>
        </div>
        {% endif %}
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr style="background: #16162a;">
                <td style="padding: 16px; text-align: center; border-radius: 8px 0 0 8px;">
                    <div style="font-size: 28px; font-weight: 700; color: #00d4ff;">{{ total_papers }}</div>
                    <div style="font-size: 12px; color: #8888aa;">Papers</div>
                </td>
                <td style="padding: 16px; text-align: center;">
                    <div style="font-size: 28px; font-weight: 700; color: #00d4ff;">{{ total_words }}</div>
                    <div style="font-size: 12px; color: #8888aa;">Words</div>
                </td>
                <td style="padding: 16px; text-align: center; border-radius: 0 8px 8px 0;">
                    <div style="font-size: 28px; font-weight: 700; color: #00d4ff;">{{ total_reading_time }}</div>
                    <div style="font-size: 12px; color: #8888aa;">Min Read</div>
                </td>
            </tr>
        </table>

        <div class="toc">
            <h4>🏆 Top Papers This Month</h4>
            <ul>
            {% for paper in top_papers %}
                <li><strong>{{ paper.title }}</strong> — {{ paper.date }}</li>
            {% endfor %}
            </ul>
        </div>

        {% for week in weeks %}
        <div class="day-section">
            <h3>Week {{ loop.index }}: {{ week.start }} – {{ week.end }}</h3>
            {{ week.content_html }}
        </div>
        {% endfor %}
    </div>
    <div class="footer">
        <p>Generated by <a href="https://github.com/Raj-Shriwastav/Research_Paper_Summarizer">Research Paper Summarizer</a></p>
        <p>You received this because you're subscribed to monthly digests.</p>
    </div>
</div>
</body></html>""")


# ──────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────

def render_daily(
    topic: str,
    date: str,
    papers: List[Dict[str, Any]],
    word_count: int = 0,
    greeting_name: str = "",
) -> str:
    """
    Render the daily digest HTML email.

    Args:
        topic: The research topic name.
        date: Date string (YYYY-MM-DD).
        papers: List of dicts with keys: title, authors, summary_html, url.
        word_count: Total word count of the digest.

    Returns:
        Fully rendered HTML string.
    """
    reading_time = max(1, word_count // 220)
    return _DAILY_TEMPLATE.render(
        styles=_BASE_STYLES,
        topic=topic,
        date=date,
        paper_count=len(papers),
        word_count=word_count,
        reading_time=reading_time,
        papers=papers,
        greeting_name=greeting_name,
    )


def render_weekly(
    topic: str,
    week_start: str,
    week_end: str,
    days: List[Dict[str, Any]],
    total_papers: int = 0,
    total_words: int = 0,
    greeting_name: str = "",
) -> str:
    """
    Render the weekly roundup HTML email.

    Args:
        topic: The research topic name.
        week_start: Start date of the week (YYYY-MM-DD).
        week_end: End date of the week (YYYY-MM-DD).
        days: List of dicts with keys: date, paper_count, paper_titles, content_html.
        total_papers: Total papers across the week.
        total_words: Total word count across the week.

    Returns:
        Fully rendered HTML string.
    """
    return _WEEKLY_TEMPLATE.render(
        styles=_BASE_STYLES,
        topic=topic,
        week_start=week_start,
        week_end=week_end,
        total_papers=total_papers,
        days_count=len(days),
        total_words=total_words,
        days=days,
        greeting_name=greeting_name,
    )


def render_monthly(
    topic: str,
    month_name: str,
    year: int,
    weeks: List[Dict[str, Any]],
    top_papers: List[Dict[str, Any]],
    total_papers: int = 0,
    total_words: int = 0,
    greeting_name: str = "",
) -> str:
    """
    Render the monthly report HTML email.

    Args:
        topic: The research topic name.
        month_name: Full month name (e.g., "May").
        year: Year number.
        weeks: List of dicts with keys: start, end, content_html.
        top_papers: List of dicts with keys: title, date.
        total_papers: Total papers in the month.
        total_words: Total word count across the month.

    Returns:
        Fully rendered HTML string.
    """
    total_reading_time = max(1, total_words // 220)
    return _MONTHLY_TEMPLATE.render(
        styles=_BASE_STYLES,
        topic=topic,
        month_name=month_name,
        year=year,
        total_papers=total_papers,
        weeks_count=len(weeks),
        total_words=total_words,
        total_reading_time=total_reading_time,
        weeks=weeks,
        top_papers=top_papers,
        greeting_name=greeting_name,
    )
